language: android
android:
  components:
    - tools
    - build-tools-26.0.1
    - platform-tools
    - android-26

  license:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
   - ./gradlew build connectedCheck


